---
abstract: 'All Git::CheckFor plugins at once'
author:
  - 'Chris Weyl <cweyl@alumni.drew.edu>'
build_requires:
  File::Find: 0
  File::Temp: 0
  File::chdir: 0
  Path::Class: 0
  Test::DZil: 0
  Test::Fatal: 0
  Test::Moose::More: 0.008
  Test::More: 0.88
  Test::TempDir: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300015, CPAN::Meta::Converter version 2.120921'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-Git-CheckFor
requires:
  Dist::Zilla::Plugin::Git::NextVersion: 1.120370
  Dist::Zilla::Role::BeforeRelease: 0
  Dist::Zilla::Role::Git::Repo: 0
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Git::Wrapper: 0
  IPC::System::Simple: 0
  List::Util: 0
  Moose: 0
  Moose::Role: 0
  MooseX::AttributeShortcuts: 0
  Try::Tiny: 0
  autodie: 0
  namespace::autoclean: 0
  perl: 5.006
resources:
  bugtracker: https://github.com/RsrchBoy/dist-zilla-pluginbundle-git-checkfor/issues
  homepage: http://metacpan.org/release/Dist-Zilla-PluginBundle-Git-CheckFor/
  repository: git://github.com/RsrchBoy/dist-zilla-pluginbundle-git-checkfor.git
version: 0.004
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Filter/NextRelease'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Filter/@Git/Check'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Filter/@Git/Commit'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Filter/@Git/Tag'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Filter/@Git/Push'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@Filter/Git::NextVersion'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      name: '@Filter/@Git::CheckFor/Git::CheckFor::CorrectBranch'
      version: 0.003
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::Fixups
      name: '@Filter/@Git::CheckFor/Git::CheckFor::Fixups'
      version: 0.003
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Filter/GatherDir'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/PruneCruft'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/License'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/ExecDir'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/ShareDir'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Filter/MakeMaker'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: '@Filter/InstallGuide'
      version: 1.101461
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/Manifest'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::SurgicalPkgVersion
      name: '@Filter/SurgicalPkgVersion'
      version: 0.0019
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: '@Filter/ReadmeFromPod'
      version: 0.16
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Filter/AutoPrereqs'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@Filter/Prepender'
      version: 1.112280
    -
      class: Dist::Zilla::Plugin::ConsistentVersionTest
      name: '@Filter/ConsistentVersionTest'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Filter/PodCoverageTests'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Filter/PodSyntaxTests'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@Filter/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@Filter/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: '@Filter/HasVersionTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: '@Filter/Test::Compile'
      version: 1.112820
    -
      class: Dist::Zilla::Plugin::Test::Portability
      name: '@Filter/Test::Portability'
      version: 2.0.2
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Filter/ExtraTests'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@Filter/MinimumPerl'
      version: 1.003
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@Filter/ReportVersions::Tiny'
      version: 1.03
    -
      class: Dist::Zilla::Plugin::NoSmartCommentsTests
      name: '@Filter/NoSmartCommentsTests'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Filter/MetaConfig'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Filter/MetaJSON'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/MetaYAML'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Filter/TestRelease'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@Filter/CheckPrereqsIndexed'
      version: 0.007
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Filter/ConfirmRelease'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/UploadToCPAN'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::GitHub::Meta
      name: '@Filter/GitHub::Meta'
      version: 0.19
    -
      class: Dist::Zilla::Plugin::GitHub::Update
      name: '@Filter/GitHub::Update'
      version: 0.19
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@Filter/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Filter/ReadmePodInRoot'
      version: 0.120120
    -
      class: Dist::Zilla::Plugin::ArchiveRelease
      name: '@Filter/ArchiveRelease'
      version: 4.00
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@Filter/InstallRelease'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300015
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300015
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300015
